env: {}

name: CI
on:
  - pull_request
  - push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn
      - name: lint
        run: yarn prettier --check .
   Build:
     steps:
     - uses: thedoctor0/zip-release@master
       with:
         filename: 'release.zip'
         exclusions: '*.git* /*node_modules/* *rc* *.psb yarn.lock package.json'
     - uses: actions/upload-artifact@v2
       with:
         path: release.zip
   
